init header without buttons
Omer-Leibo/UI pull request #30
Opened 2023-05-23 11:19 UTC by Omer-Leibo

2023-05-23 12:08 UTC, ndvisme commented on groupyz/src/assets/images/header_logo.png
No need to create this file again, it already exists in our app.

2023-05-23 12:11 UTC, ndvisme commented on groupyz/src/Header.jsx
- [ ] 'header_logo' should start with upper case --> Header_logo
- [ ] class "headerContainer', were in the header file & component , no need to right header, just container.
- [ ] HeaderLogo? why not just logo?

2023-05-23 12:14 UTC, ndvisme commented on groupyz/src/styles/Header.css
I haven't checked this yet, but it's smart to try avoiding using pixels.
I'm guessing that if I'll play with the screen size, it will ruin the header.
Again, I don't really know this, but I advise u to check it before PR.

2023-05-23 12:15 UTC, ndvisme requested changes
@Omer-Leibo, hey.
I left some comments on each file, go over them & tell me what u think.

2023-05-24 16:53 UTC, Omer-Leibo commented on groupyz/src/Header.jsx
@ndvisme regarding the HeaderContainer, I wanted to allign with your work on the footer where you named the container 'footerContainer' so it will be consistent across the project, regarding the HeaderLogo its because you have already uploaded a logo called Logo to the assets/images folder and those are logos of different sizes.

2023-05-25 08:32 UTC, ndvisme commented on groupyz/src/Header.jsx
@Omer-Leibo, 
1) If I wrote 'footerContainer',  Ishouldn't have, it's a long name for no reason. 
2) About the image.. did you check if u can change the image size?
example: https://stackabuse.com/resizing-images-with-react/

2023-05-26 21:49 UTC, ndvisme commented on groupyz/src/Header.jsx
Looks great.

2023-05-26 21:50 UTC, ndvisme commented on groupyz/src/styles/Header.css
Looks great.

2023-05-26 21:50 UTC, ndvisme approved these changes
@Omer-Leibo, great job.

2023-05-27 15:00 UTC, ndvisme approved these changes
Looks good, checking it in sandbox now

2023-05-27 15:05 UTC, ndvisme approved these changes

2023-05-27 15:05 UTC, merged